var: 5652652是的发送到发送到是的发送到发送到递四方速递
server:
  port: 8050
spring:
  datasource:
    url: jdbc:mysql://192.168.1.125/ppc?characterEncoding=utf-8&useSSL=false
    username: ppc
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.1.125
    port: 5672


