spring:
  application:
    name: order
    datasource:
      url: jdbc:mysql://192.168.1.125/ppc?characterEncoding=utf-8&useSSL=false
      username: ppc
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env: test7
girl:
  name: lilo
  age: 20
